title: kukuleaf
logo_img: /assets/img/icons/simplex_logo.svg
favicon: /assets/favicon.svg
description: description
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © kukuleaf 2025

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"