title: kukuleaf
logo_img: /assets/img/icons/simplex_logo.svg
favicon: /assets/favicon.svg
description: description
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © kukuleaf 2025

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"


title: kukuleaf
email: dbsdugns16@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kukuleaf

# Build settings
theme: minima
plugins:
  - jekyll-feed